# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/miniaig',
                'doc_host': 'https://gsgbills.github.io',
                'git_url': 'https://github.com/gsgbills/miniaig',
                'lib_path': 'miniaig'},
  'syms': {'miniaig.core': {'miniaig.core.foo': ('core.html#foo', 'miniaig/core.py')}}}
